### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by Resonanz** [catppuccin/egui#41]
Hi, can you please add build instructions:

cargo  run --example todo  // saves a beginner 15 minutes

Ubuntu:

thread 'main' panicked at build.rs:14:10:
  called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }

**Comment by Stonks3141** [comment]
Hi! Thanks for reporting this issue. I added [Whiskers](https://github.com/catppuccin/toolbox/tree/main/whiskers) as a build-time dependency not long ago and forgot to update the README. I'll also make it a warning instead of an obscure error since Whiskers isn't absolutely required to build the crate.

**Comment by Stonks3141** [comment]
Fixed by 00ddd54 and 73e0d2e.
